name       : hunspell-sr
version    : 20130715
release    : 2
source     :
    - http://devbase.net/dict-sr/hunspell-sr-20130715.zip : 2ddedbf7f0874ebb1b59829dbd73ebfe26f98aa99f19f8f7eb4e849c393a75f2
license    : GPL-2.0-or-later
component  : spelling
summary    : Serbian hunspell dictionaries
description: |
    hunspell dictionaries
rundeps    :
    - libhunspell
install    : |
    install -D -d -m 00755 $installdir/usr/share/hunspell
    install -m 00644 sr*.dic sr*.aff $installdir/usr/share/hunspell

    pushd $installdir/usr/share/hunspell/
    # RS
    ln -s sr.aff sr_RS.aff
    ln -s sr.dic sr_RS.dic
    ln -s sr-Latn.aff sr_RS-latin.aff
    ln -s sr-Latn.dic sr_RS-latin.dic

    # BiH
    ln -s sr.aff sr_BA.aff
    ln -s sr.dic sr_BA.dic
    ln -s sr-Latn.aff sr_BA-latin.aff
    ln -s sr-Latn.dic sr_BA-latin.dic
    popd
